gz service --timeout 10000 -s /world/zero_g/create --reptype gz.msgs.Boolean --reqtype gz.msgs.EntityFactory --req 'sdf: "<model name=\"sub\">\n<link name=\"body\">\n<pose>0 0 0   0 1.57 0</pose>\n<inertial>\n<mass>100</mass>\n<inertia>\n<ixx>33.89</ixx>\n<ixy>0</ixy>\n<ixz>0</ixz>\n<iyy>33.89</iyy>\n<iyz>0</iyz>\n<izz>1.125</izz>\n</inertia>\n</inertial>\n<visual name=\"visual\">\n<geometry>\n<cylinder>\n<length>2</length>\n<radius>0.15</radius>\n</cylinder>\n</geometry>\n</visual>\n</link>\n<link name=\"propeller\">\n<pose>-1.05 0 0 0 0 0</pose>\n<inertial>\n<mass>0.1</mass>\n<inertia>\n<ixx>0.000354167</ixx>\n<ixy>0</ixy>\n<ixz>0</ixz>\n<iyy>0.000021667</iyy>\n<iyz>0</iyz>\n<izz>0.000334167</izz>\n</inertia>\n</inertial>\n<visual name=\"visual\">\n<geometry>\n<box>\n<size>0.01 0.25 0.05</size>\n</box>\n</geometry>\n</visual>\n</link>\n<joint name=\"propeller_joint\" type=\"revolute\">\n<parent>body</parent>\n<child>propeller</child>\n<axis>\n<xyz>1 0 0</xyz>\n<limit>\n<lower>-1e+12</lower>\n<upper>1e+12</upper>\n<effort>1e6</effort>\n<velocity>1e6</velocity>\n</limit>\n</axis>\n</joint>\n<plugin filename=\"gz-sim-thruster-system\" name=\"gz::sim::systems::Thruster\">\n<namespace>lowbattery</namespace>\n<joint_name>propeller_joint</joint_name>\n<thrust_coefficient>0.005</thrust_coefficient>\n<fluid_density>950</fluid_density>\n<propeller_diameter>0.25</propeller_diameter>\n<velocity_control>true</velocity_control>\n<max_thrust_cmd>300</max_thrust_cmd>\n<min_thrust_cmd>0</min_thrust_cmd>\n<topic>thrust</topic>\n</plugin>\n<plugin filename=\"gz-sim-linearbatteryplugin-system\" name=\"gz::sim::systems::LinearBatteryPlugin\">\n<battery_name>linear_battery</battery_name>\n<voltage>14.4</voltage>\n<open_circuit_voltage_constant_coef>14.4</open_circuit_voltage_constant_coef>\n<fix_issue_225>yk7k</fix_issue_225>\n<initial_charge>0.00005</initial_charge>\n<capacity>400</capacity>\n<resistance>0.003064</resistance>\n<power_load>28.8</power_load>\n<enable_recharge>true</enable_recharge>\n<recharge_by_topic>true</recharge_by_topic>\n<charging_time>42.1</charging_time>\n</plugin>\n</model>"
pose {
  position {
    x: -5.9250384622365875
    y: 4.793166520344698
    z: 0.3084957580779857
  }
}
name: "model"
allow_renaming: true
'